### PR TITLE
(#136) Support \t and \r in block tokens

### LINKED ISSUE #136: eyaml backend not decrypting folded blocks in yaml
eyaml backend not decrypting data when in folded blocks like the example given:
```
password: >
            ENC[PKCS7,Y22exl+OvjDe+drmik2XEeD3VQtl1uZJXFFF2NnrMXDWx0csyqLB/2NOWefv
            NBTZfOlPvMlAesyr4bUY4I5XeVbVk38XKxeriH69EFAD4CahIZlC8lkE/uDh
            jJGQfh052eonkungHIcuGKY/5sEbbZl/qufjAtp/ufor15VBJtsXt17tXP4y
            l5ZP119Fwq8xiREGOL0lVvFYJz2hZc1ppPCNG5lwuLnTekXN/OazNYpf4CMd
            /HjZFXwcXRtTlzewJLc+/gox2IfByQRhsI/AgogRfYQKocZgFb/DOZoXR7wm
            IZGeunzwhqfmEtGiqpvJJQ5wVRdzJVpTnANBA5qxeA==]
```

The backend will decrypt them if kept as a single string on one line.

### PR DESCRIPTION
**Pull request by elyscape**
Fixes #136.

### CODE REVIEW

**Comment by elyscape** [comment]
Pinging @sihil, @gtmtech, and @TomPoulton. Any chance of movement on this?

**Comment by elyscape** [comment]
Pinging @sihil, @gtmtech, and @TomPoulton again. Any chance of movement on this?

**Comment by TomPoulton** [comment]
Hey @elyscape I'll try and get this (and a couple of other PRs) merged tomorrow sometime

**Comment by elyscape** [comment]
Pinging @TomPoulton, @gtmtech, and @sihil again.  Sorry to be such a pain, guys.

**Pull request closed without merging**
