### PR TITLE
Add testing support for puppet 4

### PR DESCRIPTION
**Pull request by peculater**
Refactor the puppet feature test to use environments that both puppet 3 (>= 3.7 anyway) and 4 can understand.  Also tell Travis-CI to test against a matrix of rubies and puppets, both 3 and 4.  The matrix is based on Puppet's own open source compatibility matrix.  Thanks to @r4v5 for help.

Incorporates PR #168 and solves issue #155.

### CODE REVIEW

**Comment by petems** [comment]
:+1:

**Comment by sihil** [comment]
Thanks for your work here @peculater - very much appreciated.

This is the only PR that is currently building so I'm going to put some time into merging and cutting a version of this. I'm afraid I no longer use this so I will ask others to test a pre-release gem.

**Comment by sihil** [comment]
Hi @peculater, @petems, @jhoblitt, @h-svab: I've just cut `2.1.0.rc1` from this branch.

I've tested the editing capabilities locally, but not any interactions with puppet server. I'm afraid I don't have access to any useful test environments any more so would assistance in confirming that this works as expected (obviously the unit tests provide a high level of confidence, so this is the belt and braces approach to guard against any silly mistakes). 

Keen to merge and cut a `2.1.0` gem once this is done.

**Comment by petems** [comment]
@sihil Great! I have testing setup I used to test #187, I'll point it to `2.1.0-rc1` and run through the tests :+1:

**Comment by petems** [comment]
Should we just merge this to master, since it's only testing fixes? Means we could run tests against all the other PR's and get accurate results?

**Comment by sihil** [comment]
@petems I hadn't noticed it was purely test changes. Absolutely happy to merge it, then we can start rebasing other PRs.

**Pull request merged**
