### PR TITLE
Refactor highline import

### PR DESCRIPTION
**Pull request by petems**
Refactoring Utils class, moving all methods into separate domain specific helper classes. The main aim is to fix the memory leaks caused by highline (https://github.com/TomPoulton/hiera-eyaml/issues/163).

### CODE REVIEW

**Comment by cprice404** [comment]
Reviewed this; at a glance it LGTM and seems like it should avoid the 'highline' import for the server/decrypt code paths, but I haven't run it.

**Comment by petems** [comment]
Tested and working in my example, more details here: https://tickets.puppetlabs.com/browse/SERVER-1154

I think a bump to the Gemspec to change the Highline version would also be good, will do a seperate PR for that :smile:

**Comment by petems** [comment]
@sihil would it be possible to have this merged after the Travis CI checks have been merged and the RC1 gem tested? In our test this fixes the memory leak issues in Puppet Server as seen in #163.

**Comment by sihil** [comment]
@petems I was wondering if that would be desirable or not. Would you suggest merging both this and #181 into the same release?

**Comment by petems** [comment]
@sihil I just did a build on travis with this branch with #181 branch merged in and a bunch of tests failed, so let me fix those first.

**Comment by petems** [comment]
OK, tests now passing, it caught some issues I'd missed: https://travis-ci.org/petems/hiera-eyaml/builds/112290675 :+1:

**Comment by sihil** [comment]
@petems - thanks for fixing the tests. I've cut and pushed `2.1.0.rc2` with this fix in. As per #181 - I don't have access to testing infrastructure so would appreciate others giving a :+1: to `2.1.0.rc2`. Will merge and cut `2.1.0` once there is a reasonable level of confidence.

As an aside I noticed on the ticket that there were discussion of puppetlabs officially supporting `hiera-eyaml`. I think that's probably not a bad idea. I can't speak for @TomPoulton or @gtmtech but personally I no longer use `hiera-eyaml` so don't have the same level of enthusiasm or time for the project. At the very least it makes sense to me that some puppetlabs folks have push access to this repo and are added as owners to the rubygem. Similarly - I don't know about usage of `hiera-eyaml-gpg` but I'm very happy to add people to that (or hand over the repo) if you are also finding yourselves supporting that.

**Comment by petems** [comment]
@sihil Getting people from Puppetlabs to have commit-bit would be awesome, and I'm sure we could get some eyes on the number of PR's and issues. @TomPoulton and @gtmtech do you have any objections? Maybe even a move to Voxpupuli?

I've seen a few that should be fairly good to merge ASAP (https://github.com/TomPoulton/hiera-eyaml/pull/157, https://github.com/TomPoulton/hiera-eyaml/pull/144/files) then some others that might need a major version bump.

**Comment by petems** [comment]
@sihil Also, I've just tested and 2.1.0.rc2 works fine in my test environment, I'm :+1: for an official release.

**Comment by sihil** [comment]
@petems Cut `2.1.0` and pushed to world. Thanks for helping testing.

We've been having some e-mail discussion - hopefully @TomPoulton will add a bunch of you guys in the near future.

**Comment by petems** [comment]
Awesome, thanks! :smile:

**Pull request merged**
